name: ctrl_alt_foo
version: 0.3.1
description: For creating simple keyboard shortcuts.
authors:
- Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/uojiaku/ctrl-alt-foo
environment:
  sdk: ">=0.8.10+6 <2.8.2"
dev_dependencies:
  #unittest: ">=0.11.0 <0.12.0"
